In [2]:
from neural_implementation import neural_classification as nc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
nn = nc.NeuralNetwork(2, [2], 1)
nn.print_network()
print()

nn.initialize_model(model_init_bounds=(-5, 5))
print('Initial model:')
nn.print_model()

~ Neural network ~
Layer 1:
[1. 1. 1.]
Layer 2:
[1. 1. 1.]
Layer 3:
[1.]

Initial model:
Model:
W_0: 0 -> 1, shape: (2, 3)
[[-1.3408351   1.64673495  3.12928405]
 [ 4.57105168 -3.18201653  3.62280449]]
W_1: 1 -> 2, shape: (1, 3)
[[-1.96289633  0.00858482 -4.74573407]]


In [4]:
w0 = np.array([
    [1, 3, 3],
    [1, 2, 2]
])

w1 = np.array([
    [1, 2, 4]
])

ws = np.array([w0, w1])
nn.set_model(ws)

nn.print_model()

Model:
W_0: 0 -> 1, shape: (2, 3)
[[1 3 3]
 [1 2 2]]
W_1: 1 -> 2, shape: (1, 3)
[[1 2 4]]


In [3]:
x = np.array([1, -5, -5])
nn.forward_propagation(x)

nn.print_network()

~ Neural network ~
Layer 1:
[ 1 -5 -5]
Layer 2:
[1.         0.54138115 0.36303673]
Layer 3:
[0.49981504]


In [4]:
X = np.vstack([
    [1, -5, 5],
    [1, 2, 3],
    [1, 4, -2],
    [1, -5, 0.5],
    [1, 1, 2],
    [1, -0.5, 0.9],
    [1, 4, 1.2],
    [1, 0.9, -0.9],
    [1, 2, 2],
    [1, 3, -2.5]
])

y = np.vstack([
    [0],
    [1],
    [0],
    [1],
    [1],
    [0],
    [1],
    [0],
    [0],
    [1]
])

In [5]:
clf = nn.fit(X, y)

print('Trained model:')
clf.print_model()

Trained model:
Model:
W_0: 0 -> 1
[[-0.08172378 -0.00714743 -0.02895801]
 [-0.08630412  0.01433589  0.02445182]]
W_1: 1 -> 2
[[ 0.01240784 -0.08896503  0.06357889]]


In [10]:
un = nc.unroll_matrix_array(nn.model)
print(un)

sizes = nc.get_matrix_sizes(nn.model)
print(sizes)

ro = nc.roll_vec_to_matrix_array(un, nc.get_matrix_sizes(nn.model))
print(ro)
ro.shape

[1. 3. 3. 1. 2. 2. 1. 2. 4.]
[(2, 3), (1, 3)]
[array([[1., 3., 3.],
       [1., 2., 2.]]) array([[1., 2., 4.]])]


(2,)

In [12]:
A = np.array([
    [1, 2, 3],
    [5, -1, 5],
    [4, -4, 2]
])

print(A.ravel())


[ 1  2  3  5 -1  5  4 -4  2]


In [4]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(x.reshape(4, 2))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
